import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../static/dashboard/sovereign-enhancements.js',import.meta.url),'utf8');
const {dailyBuffer}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const now=Date.parse('2026-09-11T12:00:00Z');
const snapshot=()=>({ok:true,timestamp:new Date(now).toISOString(),risk:{max_daily_loss_pct:.02},broker_daily_pnl:{ok:true,day_start_equity:100000,daily_pnl:-500}});
test('uses the daily-loss budget, not per-trade risk or buying power',()=>{const s=snapshot();s.risk.max_dollar_risk_per_trade=100;s.buying_power=1e9;const r=dailyBuffer(s,now);assert.equal(r.percent,75);assert.equal(r.remaining,1500);assert.equal(r.budget,2000);});
test('profits do not extend the budget and losses cannot make a negative dial',()=>{const s=snapshot();s.broker_daily_pnl.daily_pnl=5000;assert.equal(dailyBuffer(s,now).percent,100);s.broker_daily_pnl.daily_pnl=-5000;assert.equal(dailyBuffer(s,now).percent,0);});
test('missing, stale, failed and future-dated data never look healthy',()=>{for(const change of [s=>s.ok=false,s=>s.broker_daily_pnl.ok=false,s=>s.broker_daily_pnl.daily_pnl=null,s=>s.risk.max_daily_loss_pct=0,s=>s.broker_daily_pnl.day_start_equity=0,s=>s.timestamp='invalid',s=>s.timestamp=new Date(now-120001).toISOString(),s=>s.timestamp=new Date(now+60001).toISOString()]){const s=snapshot();change(s);assert.equal(dailyBuffer(s,now).available,false);}assert.equal(dailyBuffer(undefined,now).percent,null);});
test('zero P/L is valid and malformed numeric input is not',()=>{const s=snapshot();s.broker_daily_pnl.daily_pnl=0;assert.equal(dailyBuffer(s,now).percent,100);for(const v of ['',undefined,'n/a',Infinity]){s.broker_daily_pnl.daily_pnl=v;assert.equal(dailyBuffer(s,now).available,false);}});
